### ISSUE TITLE
InvalidArgumentError in char_rep_method

### ISSUE THREAD

**Issue by aopusd** [IsaacChanghau/neural_sequence_labeling#2]
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[7,11,0] = 5981 is not in [0, 5980)
[[Node: char_rep_method/char_embeddings = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@char_rep_method/_char_embeddings"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](char_rep_method/_char_embeddings/read, _arg_char_ids_0_0)]]
Caused by op 'char_rep_method/char_embeddings', defined at:

**Comment by IsaacChanghau** [comment]
@aopusd I update the codes, and rewrite the reshape methods, I am not sure why this happens, can you give more details? I remember you also email to me right? To deal with Chinese dataset?

**Comment by aopusd** [comment]
thank you very much !can i  give you my dataset?




------------------ 原始邮件 ------------------
发件人: "ZHANG HAO"<notifications@github.com>;
发送时间: 2018年3月16日(星期五) 下午2:36
收件人: "IsaacChanghau/neural_sequence_labeling"<neural_sequence_labeling@noreply.github.com>;
抄送: "奥普"<137219067@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [IsaacChanghau/neural_sequence_labeling]tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[7,11,0]= 5981 is not in [0, 5980) [[Node: char_rep_method/char_embeddings =Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, (#2)




@aopusd I update the codes, and rewrite the reshape methods, I am not sure why this happens, can you give more details? I remember you also email to me right? To deal with Chinese dataset?

**Comment by IsaacChanghau** [comment]
Sure, if it’s not so big, pls email me 

Best Regards,

Hao ZHANG
Mail: 2680819187@qq.com

**Comment by aopusd** [comment]
ok,i give you later 




------------------ 原始邮件 ------------------
发件人: "ZHANG HAO"<notifications@github.com>;
发送时间: 2018年3月16日(星期五) 下午4:17
收件人: "IsaacChanghau/neural_sequence_labeling"<neural_sequence_labeling@noreply.github.com>;
抄送: "奥普"<137219067@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [IsaacChanghau/neural_sequence_labeling] InvalidArgumentError inchar_rep_method (#2)



Sure, if it’s not so big, pls email me 
 
 Best Regards,
 
 Hao ZHANG
 Mail: 2680819187@qq.com
