### ISSUE TITLE
Question for the NER performance

### ISSUE THREAD

**Issue by jind11** [IsaacChanghau/neural_sequence_labeling#4]
hi, I am quite interested in your code on the NER task, especially, for CONLL 2003 dataset, you have stated that your best test F1 is 91.8%, which is awesome. However, it looks weird to me that the valid and test F1 scores are so close by referring to the paper "End-to-end Sequence Labeling via Bi-directional LSTM-CNNs-CRF" and my experiments. Could you check this issue? Thanks a lot!

Epoch 47/100:
703/703 [==============================] - 95s - Global Step: 33041 - Train Loss: 0.0246      
Valid dataset -- accuracy: 98.53, precision: 91.54, recall: 92.12, FB1: 91.83
 -- new BEST score on valid dataset: 91.83
Test dataset -- accuracy: 98.52, precision: 91.53, recall: 92.11, FB1: 91.82

**Comment by 26hzhang** [comment]
Sorry lah, I was wrongly use the CoNLLeval.py function, and modified it already.........
