### ISSUE TITLE
unable to achive 91.82 in ner

### ISSUE THREAD

**Issue by omerarshad** [IsaacChanghau/neural_sequence_labeling#7]
Thanks for the code, but i am unable to achieve F1 91.82 in ner by using the same config given in repo. Any help?

**Comment by TanyaZhao** [comment]
@omerarshad 
Hi friend~I also can not achieve the result 91.82. 

And I quite doubt that the hyperparameters used in this project are quite different from that used in Ma's paper (End-to-end Sequence Labeling via Bi-directional LSTM-CNNs-CRF).  The dimensions of the hyperparameters are much larger.

So, I doubt that is this comparable to Ma's model ?
btw, could you share with me what F1 score you achieve ?

Thx~

**Comment by omerarshad** [comment]
I was able to achieve 91.05 after lot of hyper parameter tuning using Glove embeddings.

**Comment by TanyaZhao** [comment]
cool !
Could you tell me some key parameters ?
I was suffering from tuning parameters for a long time, and haven't got an idea result...

**Comment by omerarshad** [comment]
what's your best score achieved?

**Comment by 26hzhang** [comment]
Sorry guys, I already changed the error information in README.md, since I was wrongly use the CoNLLeval.py function.

**Comment by omerarshad** [comment]
What did you changed? Do we need to pull your code again?
