### ISSUE TITLE
Words Embeddings + BiLSTM + CRF structure

### ISSUE THREAD

**Issue by Dragon615** [IsaacChanghau/neural_sequence_labeling#8]
Hi @IsaacChanghau ,

Thanks for your great implementation. 
I'm interested in testing the following structure as baseline system >> Words Embeddings + BiLSTM + CRF for POS tagging. I'm not sure what should be updated in the current version of the implementation to have this structure work. 
My apology if my question looks silly. 
Thanks in advance for your help.

**Comment by Dragon615** [comment]
Also is it possible to work with fasttext embeddings?

**Comment by 26hzhang** [comment]
@Dragon615 I did not try fasttext embeddings, but I think it should work, not sure the performance. For the baseline, you can remove the Char CNN part and also the char embeddings, close all the attention, residual, layer normalization and etc.
